language: java
jdk:
    - openjdk8

branches:
    only:
        - master

# Travis CI Server's home
cache:
    directories:
        - '$HOME/.m2/repository'
        - '$HOME/.gradle'

script: "./gradlew clean"

# CI 실행완료시 메일로 알림
notifications:
    email:
        recipients:
            393941932@qq.com
